recipe: default.v1
language: en
additional_languages:
  - fr
  - de
assistant_id: hello-banking
pipeline:
- name: CompactLLMCommandGenerator
  llm:
    model_group: openai-gpt-4o
  flow_retrieval:
    embeddings:
      model_group: openai-embeddings

policies:
- name: FlowPolicy
- name: EnterpriseSearchPolicy
